server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intelligent_teaching?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: 5201314zsy

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.huadi.intelligentteachingplatform.entity
  mapper-locations: classpath:com/huadi/intelligentteachingplatform/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload:
    path: uploads/
